services:
  localstack:
    container_name: localstack-c6y
    image: localstack/localstack:3.6.0
    ports:
      - "127.0.0.1:4566:4566"           # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_SOCK=/var/run/docker.sock
      - SERVICES
      - DEFAULT_REGION
      - SES_VERIFY_EMAILS
      - S3_DEFAULT_BUCKET
      - DEBUG=1
      - DISABLE_CORS_CHECKS=true
    volumes:
      - localstack-debug:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./localstack/init:/etc/localstack/init/ready.d
    networks:
      - localstack-c6y

networks:
  localstack-c6y:
    external: true

volumes:
  localstack-debug:
