version: "3.8"

services:
  php:
    build: ./php
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ../mail-provider/:/var/www/server:cached

  nginx:
    image: nginx
    ports:
      - 80:80
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ../mail-provider/:/var/www/server:cached
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php
