services:
  localstack:
    container_name: localstack-debug
    image: localstack/localstack:2.3
    ports:
      - 4566:4566              # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=s3,ses
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_SOCK=/var/run/docker.sock
      - DEFAULT_REGION
      - SES_VERIFY_EMAIL
      - S3_DEFAULT_BUCKET
      - DEBUG=1
      - DISABLE_CORS_CHECKS=true
    volumes:
      - localstack-debug:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./localstack/init:/etc/localstack/init/ready.d

volumes:
  localstack-debug:
